<MainScreen>:

    name: 'main'
    on_enter: root.start()

    magnet_button: magnet_button

    FloatLayout:
        size_hint: 1, 1

    DPEAButton:
        id: test_button
        text: 'shudown'
        size: 100, 100
        x: 1800
        y: 1000
        color: 0, 1, 0, 1
        on_press: root.shutdown()



    DPEAButton:
        id: magnet_button
        text: "magnet on"
        size: 200, 200
        x: 100
        y: 1000
        color: 1, 0, 0, 1
        on_press: root.magnet()

